Popup window js
JOdiemo/popup-window pull request #1
Opened 2022-06-24 09:40 UTC by JOdiemo

Use basic JavaScript syntax.
Use JavaScript to manipulate DOM elements.
Use JavaScript events.

2022-06-24 12:18 UTC, KDlamini requested changes
### Hi @JOdiemo 🙋‍♀️,  

Geat job so far! 💯 
You have made a great effort in creating a working popup for each project according to the Figma design.
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  Good PR title and description
✔️  Correct use of Gitflow 
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 12:18 UTC, KDlamini commented on index.html
> +                    <button type="button" class="project" data-modal-target="#modal0">See Project</button>
For this milestone: The projects section must be created dynamically with the information from the projects array you created (all the HTML of the project section is created when the page loads). **This requires changes in existing code - already created HTML code for the projects list should be removed, and instead it should be added via JavaScript.**

![image](https://user-images.githubusercontent.com/38088818/175532776-e9845f08-f99c-4232-a0e1-29c68c1773f9.png)

- You can achieve this following a similar process to the one I will explain for dynamically rendering your modals below 👇🏾

2022-06-24 12:18 UTC, KDlamini commented on index.html
> +        </div>
The way you created your modals requires one to always manually add the HTML element and then create the model using the specific data every time a new project is added. This can be very time-consuming. 

* This continues below 👇🏾

2022-06-24 12:18 UTC, KDlamini commented on js/jscontent.js
> +`,
As a result, you have an unnecessary repetition of the same code here each time you create a new modal. In this milestone, you are required to practice following JavaScript's best practices. In this case, you are not following the Don't Repeat Yourself(DRY) principle.

Instead of creating each modal one by one, you can use the projects array to map each modal on the page. This way is more manageable and scalable because:

- Adding projects in the future will be easy. You will only add it in one place - as another object in the project's array.

You can achieve this by first creating one parent container for all your modals with the empty modal skeleton in your index.html file e.g
```
    <section class="modal-container">
       <div class="modal"></div>
    <section>
```

Then select the empty modal skeleton in your js file.
```
   const modal = document.querySelector('.modal');
```

Then map all the data from the projects array dynamically e.g 
```
allContent.forEach((project) => {
    modal.insertAdjacentHTML(
      'afterbegin',
      `
        <div class='modal-header'>
            <h2 class='title'>${project.name}</h2>
            <button data-close-button type='button' class='close-button'>&times;</button>
        </div>
        <ul class='sub-title'>
            <li>${project.work[0]}</li>
            <li>${project.work[1]}</li>
            <li>${project.work[2]}</li>
        </ul>
    .... // rest of the modal content
    )
  });
```

If you need to add specific class names or id attributes to each modal, you can do this:
```
allContent.forEach((project, index) => {
    modal.setAttribute(‘id’,`modal${index}`);
    modal.classList.add(`modal${index}`);

    modal.insertAdjacentHTML(
    .... // rest of the modal content
    )
  });
```

**NOTE: The above code is just an example to give you an idea of the structure of dynamically adding content. It is not 100% accurate, therefore you might run into errors that you may need to resolve if encountered.**

2022-06-24 12:18 UTC, KDlamini commented on index.html
> +        <div class="modal2" id="modal2">
The modal is not responsive to other viewpoints. Kindly right-click on your page and click on `inspect` to see the difference in other viewpoints.

![image](https://user-images.githubusercontent.com/38088818/175529447-a9d6e7cf-a3ff-4f07-bd51-fb3d661a971e.png)

Also in mobile view, the spacing of your modal is uneven:

![image](https://user-images.githubusercontent.com/38088818/175529967-6791af35-45ac-48d8-b7ab-407fbc4c39a1.png)

2022-06-24 12:18 UTC, KDlamini commented on js/jscontent.js
> +  },
Kindly add the `live version` and `Source code` links on each project object in the array. The links must be rendered dynamically with each modal as well. You can use any URLs at this point, they don't have to be specific to the projects but they should work.

- When I click on the `See live` button I should be redirected to the URL of the live version. You can use the live version URL of your portfolio temporarily. Then use `a` tags to attach the URLs to the `href` while mapping the project's data on each modal in this section:
```
    <div class='project'><p>See Live</p><img src='image/sm1.png'></div>
    <div class='project'><p>See Source</p><img src='image/sm2.png'></div>
```
- When I click on the `See source` button I should be redirected to the URL source code (GitHub repo). You can use the GitHub repo URL of your portfolio temporarily.

2022-06-25 02:03 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @JOdiemo 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 02:03 UTC, tresorsawasawa commented on js/jscontent.js
> +  },
- [ ] As required by the previous reviewer, make sure you add the `live version` and `Source` code links on each project object in the array. The links must be rendered dynamically with each modal as well. You can use any URLs at this point, they don't have to be specific to the projects but they should work. i.e. Once you added links of each button in each object you should access them as you did for other properties of the objects.

2022-06-25 02:03 UTC, tresorsawasawa commented on js/jscontent.js
> +                  </div>
- [ ] As I mentioned in the previous comment make sure links are rendered dynamically with links you added in each modal as well.

2022-06-25 02:03 UTC, tresorsawasawa commented on style.css
> +}
- [ ] As mentioned by the previous reviewer kindly make sure you make the Popu window responsive to match the Figma design. Also to fix the overlapping issues on buttons
Here is how it looks:
![Screenshot from 2022-06-25 03-38-45](https://user-images.githubusercontent.com/83042742/175753591-7be0da43-b828-4d1e-9e02-72eda0a3d92f.png)

- [ ] Also make sure you also fix the unnecessary spacing between the **image** and **project's description** in the mobile popup as mentioned by the previous reviewer. I think you can fix that by only assigning the concerning images()e.g.: `.modal-photo > img { .... }` in the popup styling one class "name" and then styling it with: 
```
.created_class_name {
 height: 100%;
 width: 100%;
}
``` 
As their containers have a fixed width.

2022-06-25 05:25 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @JOdiemo       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

[OPTIONAL] Kindly add a screenshot to your README file showing your webpage user Interface. You can use extentions like fireshot to capturer the entire page.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 07:10 UTC, merged